project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

# Choose file structure in Crowdin
# e.g. true or false
preserve_hierarchy: false

# Files configuration
files:
  - source: "/options/locale/locale_en-US.ini"
    translation: "/options/locale/locale_%locale%.ini"
    excluded_target_languages: ["en", "tk", "nn-NO", "nb", "fa-AF", "bn-IN", "sw", "ta", "ml-IN", "eu", "lt", "tlh-AA", "hi", "bn", "eo"]
    type: "ini"
    skip_untranslated_strings: true
    export_only_approved: true
    update_option: "update_as_unapproved"
